language: C

os:
  - linux

env:
    matrix:
        - NUMPY_VERSION=1.16 PYTHON_VERSION=3.7


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create -q --yes -n test python=$PYTHON_VERSION cmake
    - source activate test
    - if [ $TRAVIS_OS_NAME == "linux" ]; then conda install -y gcc_linux-64; fi
    - conda install -q --yes numpy=$NUMPY_VERSION pytest cython numpy
    - python setup.py install

script:
    - pip install runtests
    - python ./runtests.py
    - bash check_tag.sh chealpy/version.py

deploy:
    - provider: pypi
      distributions: sdist
      user: "__token__"  # as rainwoodman for chealpy.
      password:
        secure: "TPLw+HBrBCBwOuekVaTPTA3F6Y3AVXPRp8C52pEiqGnnRoj0n3yIbQhloymOsMSqiuUZl8a7bMY/ULfyj7fZ7lAGjGMGBDL9rZwhNgBY1Ozm4DpGCDqkkDIEg55GCjEIVq5pKIeKu0e9VMJ4V2V4DgwXDp+6Bz01FaCRgGEcggs4mJ/dkKWfNPdAc+BVx3Rzrb/9IpxZaJ8HggnqYTUW3BkYaW4uYESqQ+hcPo3wjTJOH63u4SpWAD/5n9AXeyA48ic8Bhf7m76l03R/0e4O9os7dgmEcDFy52IfiaSdmfskxsmklV+4pYfM77lj/b/rI09o9yAXCemxcjsoVYUZdVOfRIuKXm5c2rJxgt7kjjkp/n5U8Kbjoa7f9D/B8Qa3fk6PHRExW1f1xpQKoQHI7T14IhtwzXHHpt12DnxKIZ4Hrg6b6bZ6Gc0oZ5TWLXVrAACXZXMFzHSYgdCAL/DgeB8eZwT7EHoF1BuQ4zwpnQ+EInYbFerRCPAw6a2dJrKNmVFFmvVZOlt6tPOWM3Sy6kvO+ZmtaNRG3Ewr/c/d9aVsfxnJvE2sh6jJ/2q/RJwlOoF64+7tE8J7JKBDRSIAVUaFO8I1n/qq6sTaHMc78x9/ioa3g4dzk/Jsy0UDEgunjD/ZOSLY4wkrGwdBG0QAgPZJ4a1cQfRa+oXiHt6UJh8="
      on:
        tags   : true
        condition : ${TRAVIS_JOB_NUMBER##*.} == 1

      # workaround for https://github.com/travis-ci/travis-ci/issues/9303
      edge:
        branch: v1.8.45
